version: "3.8"

services:
  backend:
    build:
      context: . # Le contexte part de la racine du projet
      dockerfile: backEnd/Dockerfile # Le Dockerfile est bien dans backEnd/
    image: kolyya-backend
    ports:
      - "5000:8080" # On expose le port du container vers l'h√¥te
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: ${POSTGRES_CONN}
    networks:
      - kolyya-network

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - kolyya-network

  frontend:
    build:
      context: ./frontEnd/kolyya-frontend
      dockerfile: Dockerfile
    image: kolyya-frontend
    ports:
      - "3000:80" # Accessible via http://localhost:3000
    networks:
      - kolyya-network
    depends_on:
      - backend

volumes:
  postgres-data:

networks:
  kolyya-network:
    driver: bridge
